# Generated by Django 5.0.2 on 2024-12-02 12:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalItem',
            fields=[
                ('item_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_number', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('flight_type', models.CharField(choices=[('N', 'Non-stop Flight'), ('D', 'Direct Flight')], max_length=20)),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_flights', to='magisair.city')),
                ('origin_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_flights', to='magisair.city')),
            ],
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('reference_number', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('booking_date', models.DateField()),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('flight_number', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='magisair.flight')),
            ],
        ),
        migrations.CreateModel(
            name='CrewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magisair.crewmember')),
                ('flight_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magisair.flightschedule')),
            ],
        ),
        migrations.CreateModel(
            name='FlightTicket',
            fields=[
                ('ticket_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('seat', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='magisair.flightbooking')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='magisair.flightschedule')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_items', to='magisair.flightbooking')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magisair.additionalitem')),
            ],
        ),
    ]
