# Generated by Django 5.0.2 on 2024-12-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magisair', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightschedule',
            old_name='flight_number',
            new_name='schedule_id',
        ),
    ]
